[package]
name = "music-viz"
version = "0.1.0"
edition = "2021"

[dependencies]
minimp3 = "0.5.1"
ngrammatic = "0.4.0"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
rodio = "0.17.1"
serde_json = "1.0.104"
spectrum-analyzer = "1.4.0"
