[package]
name = "music-viz"
version = "0.1.0"
edition = "2021"

[dependencies]
ngrammatic = "0.4.0"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
rodio = "0.17.1"
serde = "1.0.183"
serde_json = "1.0.104"
